version: "3.3"
services:
  caddy:
    configs:
      - source: caddy_config
        target: /etc/caddy/Caddyfile
    deploy:
      replicas: 1
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    secrets:
      - pgadmin_password
    environment:
      PGADMIN_DEFAULT_EMAIL: anthony@nezia.dev
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_password
    deploy:
      replicas: 1
  app: 
    image: nezia/missive-server:v1
    secrets:
      - db_user
      - db_password
      - private_key
      - public_key
      - google_application_credentials
      - cookie_secret
    build:
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production
    entrypoint: ["bash", "-c", "./wait-for-it.sh db:5432 -- ./migrate-and-start.sh"]
    deploy:
      replicas: 2
  db:
    secrets:
      - db_user
      - db_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/db_user)"]
      interval: 5s
      retries: 5
    deploy:
      replicas: 1

secrets:
  db_user:
    external: true
  db_password:
    external: true
  private_key:
    external: true
  public_key:
    external: true
  google_application_credentials:
    external: true
  cookie_secret:
    external: true
  pgadmin_password:
    external: true
configs:
  caddy_config:
    external: true
