version: '3.8'

services:
  app:
    build: 
      context: server/.
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/missive?schema=public
      API_KEY: secret
      JWT_SECRET: secret
      COOKIE_SECRET: secret
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma"]
      interval: 10s
      timeout: 5s
      retries: 5


volumes:
  postgres_data:
