services:
  caddy:
    volumes:
      - ./dev.Caddyfile:/etc/caddy/Caddyfile
  db:
    ports:
      - "5432:5432"
    env_file:
      - path: server/.dev.env
        required: true
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - path: server/.dev.env
        required: true
    volumes: 
      - ./server:/app
