services:
  caddy:
    volumes:
      - ./dev.Caddyfile:/etc/caddy/Caddyfile
  db:
    ports:
      - "5432:5432"
  app:
    env_file:
      - path: server/.dev.env
        required: true
    volumes: 
      - ./server/private_key.pem:/app/private_key.pem
      - ./server/public_key.pem:/app/public_key.pem
