version: "3.1"
services:
  caddy:
    volumes:
      - ./prod.Caddyfile:/etc/caddy/Caddyfile
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=anthony@nezia.dev
      - PGADMIN_DEFAULT_PASSWORD_FILE=/run/secrets/pgadmin_password
  app: 
    image: nezia/missive-server:v1
    secrets:
      - db_user
      - db_password
      - private_key
      - public_key
      - google_application_credentials
      - cookie_secret
    build:
      args:
        NODE_ENV: production
    environment:
      NODE_ENV: production

  db:
    secrets:
      - db_user
      - db_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/db_user)"]
      interval: 5s
      retries: 5
        
secrets:
  db_user:
    external: true
  db_password:
    external: true
  private_key:
    external: true
  public_key:
    external: true
  google_application_credentials:
    external: true
  cookie_secret:
    external: true
