services:
  caddy:
    volumes:
      - ./dev.Caddyfile:/etc/caddy/Caddyfile
    networks: 
      - missive-dev
  db:
    ports:
      - "5432:5432"
    networks: 
      - missive-dev
  app:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - path: server/.dev.env
        required: true
    volumes: 
      - ./server:/app
    networks: 
      - missive-dev
networks: 
  missive-dev:
    driver: bridge
