services:
  app:
    build: 
      context: server/.
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/missive?schema=public
      API_KEY: secret
      JWT_SECRET: secret
      COOKIE_SECRET: secret
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - path: server/.env
        required: true

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prisma
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U prisma"]
      interval: 5s
      retries: 5
  caddy:
    image: caddy:2
    environment:
      - CADDY_CA=https://acme-staging-v02.api.letsencrypt.org/directory
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
