!define PRIMARY_COLOR #625D92
!define SECONDARY_COLOR #353446
!define ACCENT_COLOR #957DAD
!define TEXT_PRIMARY_COLOR #EDEDED
!define TEXT_SECONDARY_COLOR #C4C4C4
!define ERROR_COLOR #D291BC

!include general.puml