import 'package:realm/realm.dart';

part 'pending_messages.realm.dart';

/// Represents a collection of pending messages that have not been able to be sent due to network issues.
///
/// ## Attributes:
/// - [id]: The unique identifier of the collection of messages (generated by the client).
/// - [messages]: A list of [_PendingMessage] objects that are pending to be sent.
@RealmModel()
class _PendingMessages {
  @PrimaryKey()
  late String id;
  late List<_PendingMessage> messages;
}

/// Represents a message that is pending to be sent. This is used to store messages that have not been able to be send due to network issues.
///
/// ## Attributes:
/// - [id]: The unique identifier of the message (generated by the client).
/// - [ciphertextMessage]: The encrypted message to be sent (as a [CiphertextMessage], base64 encoded).
/// - [receiver]: The name of the recipient of the message.
@RealmModel()
class _PendingMessage {
  @PrimaryKey()
  late String id;
  late String ciphertextMessage;
  late String receiver;
}
