// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzCvXf26gt4plteciJ3m9PJCpVk9xDbwM',
    appId: '1:880440055356:web:2f3d4bde18dff30a41d539',
    messagingSenderId: '880440055356',
    projectId: 'missive-a3896',
    authDomain: 'missive-a3896.firebaseapp.com',
    storageBucket: 'missive-a3896.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsNk4fWbQFiAaHh9qu_iU08LT5xBZ63Tc',
    appId: '1:880440055356:android:b9b4757efbc5200441d539',
    messagingSenderId: '880440055356',
    projectId: 'missive-a3896',
    storageBucket: 'missive-a3896.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmWFKj8yOskzpBBqQgVzRKsqIvT_Z-MME',
    appId: '1:880440055356:ios:8c5eda28c6a7e88141d539',
    messagingSenderId: '880440055356',
    projectId: 'missive-a3896',
    storageBucket: 'missive-a3896.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmWFKj8yOskzpBBqQgVzRKsqIvT_Z-MME',
    appId: '1:880440055356:ios:8c5eda28c6a7e88141d539',
    messagingSenderId: '880440055356',
    projectId: 'missive-a3896',
    storageBucket: 'missive-a3896.appspot.com',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzCvXf26gt4plteciJ3m9PJCpVk9xDbwM',
    appId: '1:880440055356:web:11fea2a476ec37ca41d539',
    messagingSenderId: '880440055356',
    projectId: 'missive-a3896',
    authDomain: 'missive-a3896.firebaseapp.com',
    storageBucket: 'missive-a3896.appspot.com',
  );
}
