name: Documentation
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-client-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Build documentation
        run: |
          cd client
          dart doc --output='public'

      - name: Prepare combined directory for client docs
        run: |
          mkdir -p combined/client-api
          mv client/public/* combined/client-api/

      - name: Upload client documentation
        uses: actions/upload-artifact@v4
        with:
          name: client-docs
          path: combined/client-api

  build-server-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Prepare Python environment
        run: |
          cd documentation
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs

      - name: Build documentation
        env:
          ENABLE_PDF_EXPORT: 1
        run: |
          cd documentation
          source venv/bin/activate
          mkdocs build --verbose --site-dir public

      - name: Prepare combined directory for server docs
        run: |
          mkdir -p combined
          mv documentation/public/* combined/

      - name: Upload server documentation
        uses: actions/upload-artifact@v4
        with:
          name: server-docs
          path: combined

  combine-artifacts:
    runs-on: ubuntu-latest
    needs: [build-client-docs, build-server-docs]
    steps:
      - name: Download client documentation
        uses: actions/download-artifact@v4
        with:
          name: client-docs
          path: combined/client-api
          
      - name: Download server documentation
        uses: actions/download-artifact@v4
        with:
          name: server-docs
          path: combined

      - name: Upload combined documentation
        uses: actions/upload-pages-artifact@v3
        with:
          path: combined

  deploy:
    runs-on: ubuntu-latest
    needs: combine-artifacts
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
