name: Unit tests
permissions:
  checks: write
on:
  push:
    branches:
      - main
jobs:
  server-unit-tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    env:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      DATABASE_URL: postgres://test:test@localhost:5432/test
      COOKIE_SECRET: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install server dependencies
        run: |
          cd server
          npm install
          npx prisma generate
          npx prisma migrate deploy
          npx prisma db seed
          openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in private_key.pem -out public_key.pem

      - name: Run server tests
        run: npm test
        working-directory: server

      - name: Upload server test report
        uses: actions/upload-artifact@v4
        with:
          name: server-test-report
          path: server/junit-report.xml

  client-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Install client dependencies
        run: |
          cd client
          flutter pub get
          dart pub global activate junitreport

      - name: Run client tests
        run: |
          cd client
          flutter test --machine | dart pub global run junitreport:tojunit --output junit-report.xml

      - name: Upload client test report
        uses: actions/upload-artifact@v4
        with:
          name: client-test-report
          path: client/junit-report.xml

  publish-tests:
    runs-on: ubuntu-latest
    needs: [server-unit-tests, client-unit-tests]
    steps:
      - name: Download server test report
        uses: actions/download-artifact@v4
        with:
          name: server-test-report
          path: server

      - name: Download client test report
        uses: actions/download-artifact@v4
        with:
          name: client-test-report
          path: client

      - name: Test report
        uses: dorny/test-reporter@v2
        with:
          report_paths: '**/junit-report.xml'
          reporter: jest-junit
