name: Unit tests
permissions:
  checks: write
on:
  push:
    branches:
      - main
jobs:
  server-unit-tests:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
    env:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      DATABASE_URL: postgres://test:test@localhost:5432/test
      COOKIE_SECRET: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'

      - name: Install server dependencies
        working-directory: server
        run: |
          npm install
          npx prisma generate
          npx prisma migrate deploy
          npx prisma db seed
          openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in private_key.pem -out public_key.pem

      - name: Run server tests
        run: npm test
        working-directory: server
      - uses: dorny/test-reporter@v2
        with:
          name: JEST tests
          path: 'server/*.xml'
          reporter: jest-junit

  client-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Run client tests
        working-directory: client
        run: flutter test --machine

      - uses: dorny/test-reporter@v2
        with:
          name: Flutter tests
          path: 'client/reports/*.json'
          reporter: flutter-json
